Enterprise/Enterprise/Controllers/ItemTypeController.cs
using Enterprise.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Dropbox.Api;
using Dropbox.Api.Files;

namespace Enterprise.Controllers
{
    [Authorize(Roles = "RegisteredUser")]

    public class ItemTypeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ItemType
        public ActionResult Index()
        {
            var itemTypes = db.ItemTypes.Include(p => p.Category);
            return View(itemTypes.ToList());
        }

        //GET: Properties/Create
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemTypes.Find(id);
            if(itemType == null)
            {
                return HttpNotFound();
            }
            return View(itemType);
        }

        public ActionResult Create() {
            ViewBag.CategoryId = new SelectList(db.Categories,"Id","Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryId,Name")] HttpPostedFileBase Image , ItemType itemType)
        {

            if (ModelState.IsValid)
            {
                if (Image == null)
                {
                    ModelState.AddModelError("Image", "Image cannot be empty");
                    ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", itemType.CategoryId);
                    return View(itemType);
                }
                else
                



                    if (!db.ItemTypes.Any(i => i.Name == itemType.Name))
                    {
                        string accessToken = "rLO2hkO01AAAAAAAAABGip4dgqIUMoDGUcO0qvfukgANmcBQTL7_B2LvRb0hRf2";
                        using (DropboxClient client =
                              new DropboxClient(accessToken, new DropboxClientConfig(ApplicationName)))
                        {
                            string[] spitInputFileName = Image.FileName.Split(new string[] { "\\" }, StringSplitOptions.RemoveEmptyEntries);
                            string fileNameAndExtension = spitInputFileName[spitInputFileName.Length - 1];

                            string[] fileNameAndExtensionSplit = fileNameAndExtension.Split('.');
                            string originalFileName = fileNameAndExtensionSplit[0];
                            string originalExtension = fileNameAndExtensionSplit[1];


                            String fileName = "@/Images/" + originalFileName + Guid.NewGuid().ToString().Replace("-", "") + "." + originalExtension;
                            var updated = client.Files.UploadAsync(
                                  fileName,
                                  mode: WriteMode.Overwrite.Overwrite.Instance,
                                 body: Image.InputStream).Result;

                            var result = client.Sharing.CreateSharedLinkWithSettingsAsync(fileName).Result;
                            itemType.ImageUrl = result.Name;
                            itemType.Image = result.Url.Replace("?dl=0", "?raw=1");


                        }
                        db.ItemTypes.Add(itemType);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                
            }

            

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", itemType.CategoryId);
            return View(itemType);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemTypes.Find(id);
            if (itemType == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", itemType.CategoryId);
            return View(itemType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryId,Name")] ItemType itemType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", itemType.CategoryId);
            return View(itemType);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemTypes.Find(id);
            if (itemType == null)
            {
                return HttpNotFound();
            }
            return View(itemType);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemType itemType = db.ItemTypes.Find(id);
            db.ItemTypes.Remove(itemType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult UploadImage()
        {
            return View();
        }


        static string ApplicationName = "Enterprise";

        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase file )
        {
            ItemType itemType = new ItemType(); ;
            string accessToken = "****";
            using (DropboxClient client =
                 new DropboxClient(accessToken, new DropboxClientConfig(ApplicationName)))
            {
                string[] spitInputFileName = file.FileName.Split(new string[] { "\\" }, StringSplitOptions.RemoveEmptyEntries);
                string fileNameAndExtension = spitInputFileName[spitInputFileName.Length - 1];

                string[] fileNameAndExtensionSplit = fileNameAndExtension.Split('.');
                string originalFileName = fileNameAndExtensionSplit[0];
                string originalExtension = fileNameAndExtensionSplit[1];


                String fileName = "@/Images/"+originalFileName+Guid.NewGuid().ToString().Replace("-","") +"."+ originalExtension;
                var updated = client.Files.UploadAsync(
                      fileName,
                      mode: WriteMode.Overwrite.Overwrite.Instance,
                      body: file.InputStream).Result;

                var result = client.Sharing.CreateSharedLinkWithSettingsAsync(fileName).Result;
                itemType.Image = result.Url.Replace("?dl=0","?raw=1");


            }
            db.ItemTypes.Add(itemType);
            db.SaveChanges();
            return RedirectToAction("Index" );

        }




        public ActionResult ViewImage(String imageUrl)
        {
            throw new NotImplementedException();
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



    }
}

Enterprise/Enterprise/Views/ItemType/Create.cshtml
@model Enterprise.Models.ItemType

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Type</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

   <div class="form-group">
       @Html.LabelFor(model=>model.Image, new { @class = "control-label col-md-2" })
       <div class="col-md-10">
           <input type="file" name="Image" id="Image" />
           @Html.ValidationMessageFor(model=>model.Image,"", new {@class = "text-danger" })
       </div>
   </div>

    @*@using (Html.BeginForm("Create", "ItemType", FormMethod.Post,
                                new { enctype = "multipart/form-data" }))
    {
        <label for="Image">Upload Image:</label>
        <input type="file" name="Image" id="Image" style="width: 100%;" />

    }*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Enterprise/Enterprise/Views/ItemType/Delete.cshtml
@model Enterprise.Models.ItemType

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Type</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>



    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Enterprise/Enterprise/Views/ItemType/Details.cshtml
@model Enterprise.Models.ItemType

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Types</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Enterprise/Enterprise/Views/ItemType/Edit.cshtml
@model Enterprise.Models.ItemType

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Type</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Enterprise/Enterprise/Views/ItemType/Index.cshtml
@model IEnumerable<Enterprise.Models.ItemType>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Enterprise/Enterprise/Views/ItemType/UploadImage.cshtml
@{
    ViewBag.Title = "UploadImage";
}

<h2>UploadImage</h2>

@using (Html.BeginForm("UploadImage", "ItemType", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    <label for="file">Upload Image:</label>
    <input type="file" name="file" id="file" style="width: 100%;" />

    <input type="submit" value="Upload" class="submit"/>
}